/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.66
 * Generated at: 2021-11-08 12:07:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import static poly.util.CmmUtil.nvl;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/view/sidebar.jsp", Long.valueOf(1635062968000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("static poly.util.CmmUtil.nvl");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

	String user_seq = (String) request.getAttribute("user_seq");
	String user_id = (String) request.getAttribute("user_id");
	String user_pwd = (String) request.getAttribute("user_pwd");
	String user_email = (String) request.getAttribute("user_email");
	String join_dt = (String) request.getAttribute("join_dt");

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("<title>Spoilbroth_StudyGroup</title>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta name=\"viewport\"\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("\n");
      out.write("<link\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700\"\n");
      out.write("	rel=\"stylesheet\">\n");
      out.write("<link\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i&display=swap\"\n");
      out.write("	rel=\"stylesheet\">\n");
      out.write("<link\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Abril+Fatface&display=swap\"\n");
      out.write("	rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"/andrea-master/css/open-iconic-bootstrap.min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/animate.css\">\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/owl.carousel.min.css\">\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"/andrea-master/css/owl.theme.default.min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/magnific-popup.css\">\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/aos.css\">\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/ionicons.min.css\">\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"/andrea-master/css/bootstrap-datepicker.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/jquery.timepicker.css\">\n");
      out.write("\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/flaticon.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/icomoon.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/style.css\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body data-aos-easing=\"slide\" data-aos-duration=\"800\" data-aos-delay=\"0\">\n");
      out.write("\n");
      out.write("	<div id=\"colorlib-page\">\n");
      out.write("	\n");
      out.write("		<!-- START 상단 NANI -->\n");
      out.write("		\n");
      out.write("		<!-- END 상단 NANI -->\n");
      out.write("		\n");
      out.write("		<!-- START 왼쪽 NANI -->\n");
      out.write("		");
      out.write('\n');
      out.write('\n');


	String id = nvl((String)session.getAttribute("user_id"));
	String date = nvl((String)session.getAttribute("join_dt")); 

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<!-- 구글폰트 -->\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Do+Hyeon&family=Nanum+Pen+Script&display=swap\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<a href=\"#\" class=\"js-colorlib-nav-toggle colorlib-nav-toggle\"><i></i></a>\n");
      out.write("		<aside id=\"colorlib-aside\" role=\"complementary\" class=\"js-fullheight\"\n");
      out.write("			style=\"height: 812px;\">\n");
      out.write("			\n");
      out.write("			<nav id=\"colorlib-main-menu\" role=\"navigation\">\n");
      out.write("			<a href=\"single.html\" class=\"img img-2\" style=\"background-image: url(/andrea-master/images/image_1.jpg);\"></a>\n");
      out.write("			<div class=\"colorlib-active\">\n");
      out.write("			<ul>\n");
      out.write("				<li>\n");
      out.write("					");
if(date.isEmpty()) { 
      out.write("\n");
      out.write("						<a href=\"/user/login.do\" style=\"font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive; font-size: 32px;\">가입 하시겠습니까?</a>\n");
      out.write("					");
 } else { 
      out.write("\n");
      out.write("						<a href=\"#\" style=\"font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive; font-size: 24px;\" method=post>첫방문  : ");
      out.print(date );
      out.write("</a>\n");
      out.write("					");
} 
      out.write("\n");
      out.write("				\n");
      out.write("				</li>\n");
      out.write("				<li>\n");
      out.write("					");
if(id.isEmpty()) { 
      out.write("\n");
      out.write("						<a href=\"/user/login.do\" style= \"font-family: 'Nanum Pen Script', cursive; font-size: 20px; padding-left: 70px;\">Sign in</a>\n");
      out.write("					");
 } else { 
      out.write("\n");
      out.write("						<a href=\"/user/logOut.do\" style=\" font-family: 'Nanum Pen Script', cursive; font-size: 24px; padding-left: 40px;\">");
      out.print(id );
      out.write(" 님 Log out</a>\n");
      out.write("					");
} 
      out.write("\n");
      out.write("				</li>\n");
      out.write("			</ul>\n");
      out.write("		</div>\n");
      out.write("		<hr style=\" width: 90%; height: 1.5px; border: none; background-color: #666666;\"/>\n");
      out.write("				<ul class=\"nav2\">\n");
      out.write("					<li class=\"colorlib-active\"><a href=\"/spoilbroth/mystudy.do\">Home</a></li>\n");
      out.write("					<li class=\"nana\"><a href=\"/mbti/mbtimain.do\">MBTI Analysis</a></li>\n");
      out.write("					<li class=\"nana2\"><a href=\"/study/match.do\">Study Matching</a></li>\n");
      out.write("					<li class=\"nana3\"><a href=\"/study/contest.do\">Study Imformation</a></li>\n");
      out.write("					<li class=\"nana4\"><a href=\"/mypage/setting.do\">Setting</a></li>\n");
      out.write("				</ul>\n");
      out.write("			</nav>\n");
      out.write("\n");
      out.write("			<div class=\"colorlib-footer\" style=\"padding-bottom: 20px;\">\n");
      out.write("				<h1 id=\"colorlib-logo\" class=\"mb-4\">\n");
      out.write("					<a href=\"/spoilbroth/main.do\" style=\"background-image: url(/andrea-master/images/bg_1.jpg); font-size: 57px;\">Spoilbroth</a>\n");
      out.write("				</h1>\n");
      out.write("				<span style=\"font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive; font-size: 28px;\">요리사가 너무 많으면 수프를 망친다.</span>\n");
      out.write("				<div class=\"mb-4\">\n");
      out.write("					<h3>Subscribe for Spoilbroth</h3>\n");
      out.write("					<form action=\"#\" class=\"colorlib-subscribe-form\">\n");
      out.write("						<div class=\"form-group d-flex\">\n");
      out.write("							<div class=\"icon\">\n");
      out.write("								<span class=\"icon-paper-plane\"></span>\n");
      out.write("							</div>\n");
      out.write("							<input type=\"text\" class=\"form-control\"\n");
      out.write("								placeholder=\"Enter Email Address\">\n");
      out.write("						</div>\n");
      out.write("					</form>\n");
      out.write("				</div>\n");
      out.write("				\n");
      out.write("			</div>\n");
      out.write("		</aside>\n");
      out.write("\n");
      out.write("\n");
      out.write("<script src=\"/andrea-master/js/jquery.min.js\"></script>\n");
      out.write("</body>\n");
      out.write("<script>\n");
      out.write("$(function(){\n");
      out.write("    var url = window.location.pathname;  \n");
      out.write("    var activePage = url.substring(url.lastIndexOf('/')+1);\n");
      out.write("    console.log(\"activePage: \" + activePage);\n");
      out.write("    \n");
      out.write("    $('.nav2 li a').each(function(){  \n");
      out.write("        var currentPage = this.href.substring(this.href.lastIndexOf('/')+1);\n");
      out.write("		console.log(\"currentPage : \"+currentPage)\n");
      out.write("		\n");
      out.write("        if (activePage == currentPage) {\n");
      out.write("        	$(\".nav2\").find(\".colorlib-active\").removeClass(\"colorlib-active\");\n");
      out.write("            $(this).parent().addClass('colorlib-active');\n");
      out.write("            $(this).addClass('colorlib-active');\n");
      out.write("            \n");
      out.write("        }else if(activePage == \"mbtianalysis.do\"){\n");
      out.write("        	$(\".nav2\").find(\".colorlib-active\").removeClass(\"colorlib-active\");\n");
      out.write("        	$('.nana').addClass('colorlib-active');\n");
      out.write("        }else if(activePage == \"match2.do\"){\n");
      out.write("        	$(\".nav2\").find(\".colorlib-active\").removeClass(\"colorlib-active\");\n");
      out.write("        	$('.nana2').addClass('colorlib-active');\n");
      out.write("        }\n");
      out.write("    });\n");
      out.write("})\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("</html>");
      out.write("\n");
      out.write("		<!-- END 왼쪽 NANI -->\n");
      out.write("		\n");
      out.write("		<div id=\"colorlib-main\">\n");
      out.write("\n");
      out.write("			<section class=\"ftco-section ftco-no-pt ftco-no-pb\">\n");
      out.write("				<div class=\"container\">\n");
      out.write("					<div class=\"row d-flex\">\n");
      out.write("						<div class=\"col-xl-8 py-5 px-md-5\">\n");
      out.write("							<div class=\"row pt-md-4\">\n");
      out.write("								<div class=\"col-md-12\">\n");
      out.write("									<div\n");
      out.write("										class=\"blog-entry ftco-animate d-md-flex fadeInUp ftco-animated\">\n");
      out.write("										<a href=\"single.html\" class=\"img img-2\"\n");
      out.write("											style=\"background-image: url(/andrea-master/images/image_1.jpg);\"></a>\n");
      out.write("										<div class=\"text text-2 pl-md-4\">\n");
      out.write("											<h3 class=\"mb-2\">\n");
      out.write("												<a href=\"single.html\">A Loving Heart is the Truest\n");
      out.write("													Wisdom</a>\n");
      out.write("											</h3>\n");
      out.write("											<div class=\"meta-wrap\">\n");
      out.write("												<p class=\"meta\">\n");
      out.write("													<span><i class=\"icon-calendar mr-2\"></i>June 28,\n");
      out.write("														2019</span> <span><a href=\"single.html\"><i\n");
      out.write("															class=\"icon-folder-o mr-2\"></i>Travel</a></span> <span><i\n");
      out.write("														class=\"icon-comment2 mr-2\"></i>5 Comment</span>\n");
      out.write("												</p>\n");
      out.write("											</div>\n");
      out.write("											<p class=\"mb-4\">A small river named Duden flows by their\n");
      out.write("												place and supplies it with the necessary regelialia.</p>\n");
      out.write("											<p>\n");
      out.write("												<a href=\"#\" class=\"btn-custom\">Read More <span\n");
      out.write("													class=\"ion-ios-arrow-forward\"></span></a>\n");
      out.write("											</p>\n");
      out.write("										</div>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"col-md-12\">\n");
      out.write("									<div\n");
      out.write("										class=\"blog-entry ftco-animate d-md-flex fadeInUp ftco-animated\">\n");
      out.write("										<a href=\"single.html\" class=\"img img-2\"\n");
      out.write("											style=\"background-image: url(/andrea-master/images/image_2.jpg);\"></a>\n");
      out.write("										<div class=\"text text-2 pl-md-4\">\n");
      out.write("											<h3 class=\"mb-2\">\n");
      out.write("												<a href=\"single.html\">Great Things Never Came from\n");
      out.write("													Comfort Zone</a>\n");
      out.write("											</h3>\n");
      out.write("											<div class=\"meta-wrap\">\n");
      out.write("												<p class=\"meta\">\n");
      out.write("													<span><i class=\"icon-calendar mr-2\"></i>June 28,\n");
      out.write("														2019</span> <span><a href=\"single.html\"><i\n");
      out.write("															class=\"icon-folder-o mr-2\"></i>Travel</a></span> <span><i\n");
      out.write("														class=\"icon-comment2 mr-2\"></i>5 Comment</span>\n");
      out.write("												</p>\n");
      out.write("											</div>\n");
      out.write("											<p class=\"mb-4\">A small river named Duden flows by their\n");
      out.write("												place and supplies it with the necessary regelialia.</p>\n");
      out.write("											<p>\n");
      out.write("												<a href=\"#\" class=\"btn-custom\">Read More <span\n");
      out.write("													class=\"ion-ios-arrow-forward\"></span></a>\n");
      out.write("											</p>\n");
      out.write("										</div>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"col-md-12\">\n");
      out.write("									<div\n");
      out.write("										class=\"blog-entry ftco-animate d-md-flex fadeInUp ftco-animated\">\n");
      out.write("										<a href=\"single.html\" class=\"img img-2\"\n");
      out.write("											style=\"background-image: url(/andrea-master/images/image_3.jpg);\"></a>\n");
      out.write("										<div class=\"text text-2 pl-md-4\">\n");
      out.write("											<h3 class=\"mb-2\">\n");
      out.write("												<a href=\"single.html\">Paths Are Made by Walking</a>\n");
      out.write("											</h3>\n");
      out.write("											<div class=\"meta-wrap\">\n");
      out.write("												<p class=\"meta\">\n");
      out.write("													<span>Dec 14, 2018</span> <span><a\n");
      out.write("														href=\"single.html\">Lifestyle</a></span> <span>5 Comment</span>\n");
      out.write("												</p>\n");
      out.write("											</div>\n");
      out.write("											<p class=\"mb-4\">A small river named Duden flows by their\n");
      out.write("												place and supplies it with the necessary regelialia.</p>\n");
      out.write("											<p>\n");
      out.write("												<a href=\"#\" class=\"btn-custom\">Read More <span\n");
      out.write("													class=\"ion-ios-arrow-forward\"></span></a>\n");
      out.write("											</p>\n");
      out.write("										</div>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"col-md-12\">\n");
      out.write("									<div\n");
      out.write("										class=\"blog-entry ftco-animate d-md-flex fadeInUp ftco-animated\">\n");
      out.write("										<a href=\"single.html\" class=\"img img-2\"\n");
      out.write("											style=\"background-image: url(/andrea-master/images/image_4.jpg);\"></a>\n");
      out.write("										<div class=\"text text-2 pl-md-4\">\n");
      out.write("											<h3 class=\"mb-2\">\n");
      out.write("												<a href=\"single.html\">The Secret of Getting Ahead is\n");
      out.write("													Getting Started</a>\n");
      out.write("											</h3>\n");
      out.write("											<div class=\"meta-wrap\">\n");
      out.write("												<p class=\"meta\">\n");
      out.write("													<span>Dec 14, 2018</span> <span><a\n");
      out.write("														href=\"single.html\">Nature</a></span> <span>5 Comment</span>\n");
      out.write("												</p>\n");
      out.write("											</div>\n");
      out.write("											<p class=\"mb-4\">A small river named Duden flows by their\n");
      out.write("												place and supplies it with the necessary regelialia.</p>\n");
      out.write("											<p>\n");
      out.write("												<a href=\"#\" class=\"btn-custom\">Read More <span\n");
      out.write("													class=\"ion-ios-arrow-forward\"></span></a>\n");
      out.write("											</p>\n");
      out.write("										</div>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"col-md-12\">\n");
      out.write("									<div\n");
      out.write("										class=\"blog-entry ftco-animate d-md-flex fadeInUp ftco-animated\">\n");
      out.write("										<a href=\"single.html\" class=\"img img-2\"\n");
      out.write("											style=\"background-image: url(/andrea-master/images/image_5.jpg);\"></a>\n");
      out.write("										<div class=\"text text-2 pl-md-4\">\n");
      out.write("											<h3 class=\"mb-2\">\n");
      out.write("												<a href=\"single.html\">You Can't Blame Gravity for\n");
      out.write("													Falling in Love</a>\n");
      out.write("											</h3>\n");
      out.write("											<div class=\"meta-wrap\">\n");
      out.write("												<p class=\"meta\">\n");
      out.write("													<span>Dec 14, 2018</span> <span><a\n");
      out.write("														href=\"single.html\">Lifestyle</a></span> <span>5 Comment</span>\n");
      out.write("												</p>\n");
      out.write("											</div>\n");
      out.write("											<p class=\"mb-4\">A small river named Duden flows by their\n");
      out.write("												place and supplies it with the necessary regelialia.</p>\n");
      out.write("											<p>\n");
      out.write("												<a href=\"#\" class=\"btn-custom\">Read More <span\n");
      out.write("													class=\"ion-ios-arrow-forward\"></span></a>\n");
      out.write("											</p>\n");
      out.write("										</div>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"col-md-12\">\n");
      out.write("									<div\n");
      out.write("										class=\"blog-entry ftco-animate d-md-flex fadeInUp ftco-animated\">\n");
      out.write("										<a href=\"single.html\" class=\"img img-2\"\n");
      out.write("											style=\"background-image: url(/andrea-master/images/image_6.jpg);\"></a>\n");
      out.write("										<div class=\"text text-2 pl-md-4\">\n");
      out.write("											<h3 class=\"mb-2\">\n");
      out.write("												<a href=\"single.html\">You Can't Blame Gravity for\n");
      out.write("													Falling in Love</a>\n");
      out.write("											</h3>\n");
      out.write("											<div class=\"meta-wrap\">\n");
      out.write("												<p class=\"meta\">\n");
      out.write("													<span>Dec 14, 2018</span> <span><a\n");
      out.write("														href=\"single.html\">Travel</a></span> <span>5 Comment</span>\n");
      out.write("												</p>\n");
      out.write("											</div>\n");
      out.write("											<p class=\"mb-4\">A small river named Duden flows by their\n");
      out.write("												place and supplies it with the necessary regelialia.</p>\n");
      out.write("											<p>\n");
      out.write("												<a href=\"#\" class=\"btn-custom\">Read More <span\n");
      out.write("													class=\"ion-ios-arrow-forward\"></span></a>\n");
      out.write("											</p>\n");
      out.write("										</div>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"col-md-12\">\n");
      out.write("									<div\n");
      out.write("										class=\"blog-entry ftco-animate d-md-flex fadeInUp ftco-animated\">\n");
      out.write("										<a href=\"single.html\" class=\"img img-2\"\n");
      out.write("											style=\"background-image: url(/andrea-master/images/image_7.jpg);\"></a>\n");
      out.write("										<div class=\"text text-2 pl-md-4\">\n");
      out.write("											<h3 class=\"mb-2\">\n");
      out.write("												<a href=\"single.html\">You Can't Blame Gravity for\n");
      out.write("													Falling in Love</a>\n");
      out.write("											</h3>\n");
      out.write("											<div class=\"meta-wrap\">\n");
      out.write("												<p class=\"meta\">\n");
      out.write("													<span>Dec 14, 2018</span> <span><a\n");
      out.write("														href=\"single.html\">Travel</a></span> <span>5 Comment</span>\n");
      out.write("												</p>\n");
      out.write("											</div>\n");
      out.write("											<p class=\"mb-4\">A small river named Duden flows by their\n");
      out.write("												place and supplies it with the necessary regelialia.</p>\n");
      out.write("											<p>\n");
      out.write("												<a href=\"#\" class=\"btn-custom\">Read More <span\n");
      out.write("													class=\"ion-ios-arrow-forward\"></span></a>\n");
      out.write("											</p>\n");
      out.write("										</div>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"col-md-12\">\n");
      out.write("									<div\n");
      out.write("										class=\"blog-entry ftco-animate d-md-flex fadeInUp ftco-animated\">\n");
      out.write("										<a href=\"single.html\" class=\"img img-2\"\n");
      out.write("											style=\"background-image: url(/andrea-master/images/image_8.jpg);\"></a>\n");
      out.write("										<div class=\"text text-2 pl-md-4\">\n");
      out.write("											<h3 class=\"mb-2\">\n");
      out.write("												<a href=\"single.html\">You Can't Blame Gravity for\n");
      out.write("													Falling in Love</a>\n");
      out.write("											</h3>\n");
      out.write("											<div class=\"meta-wrap\">\n");
      out.write("												<p class=\"meta\">\n");
      out.write("													<span><i class=\"icon-calendar mr-2\"></i>June 28,\n");
      out.write("														2019</span> <span><a href=\"single.html\"><i\n");
      out.write("															class=\"icon-folder-o mr-2\"></i>Travel</a></span> <span><i\n");
      out.write("														class=\"icon-comment2 mr-2\"></i>5 Comment</span>\n");
      out.write("												</p>\n");
      out.write("											</div>\n");
      out.write("											<p class=\"mb-4\">A small river named Duden flows by their\n");
      out.write("												place and supplies it with the necessary regelialia.</p>\n");
      out.write("											<p>\n");
      out.write("												<a href=\"#\" class=\"btn-custom\">Read More <span\n");
      out.write("													class=\"ion-ios-arrow-forward\"></span></a>\n");
      out.write("											</p>\n");
      out.write("										</div>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"col-md-12\">\n");
      out.write("									<div class=\"blog-entry ftco-animate d-md-flex\">\n");
      out.write("										<a href=\"single.html\" class=\"img img-2\"\n");
      out.write("											style=\"background-image: url(/andrea-master/images/image_9.jpg);\"></a>\n");
      out.write("										<div class=\"text text-2 pl-md-4\">\n");
      out.write("											<h3 class=\"mb-2\">\n");
      out.write("												<a href=\"single.html\">You Can't Blame Gravity for\n");
      out.write("													Falling in Love</a>\n");
      out.write("											</h3>\n");
      out.write("											<div class=\"meta-wrap\">\n");
      out.write("												<p class=\"meta\">\n");
      out.write("													<span><i class=\"icon-calendar mr-2\"></i>June 28,\n");
      out.write("														2019</span> <span><a href=\"single.html\"><i\n");
      out.write("															class=\"icon-folder-o mr-2\"></i>Travel</a></span> <span><i\n");
      out.write("														class=\"icon-comment2 mr-2\"></i>5 Comment</span>\n");
      out.write("												</p>\n");
      out.write("											</div>\n");
      out.write("											<p class=\"mb-4\">A small river named Duden flows by their\n");
      out.write("												place and supplies it with the necessary regelialia.</p>\n");
      out.write("											<p>\n");
      out.write("												<a href=\"#\" class=\"btn-custom\">Read More <span\n");
      out.write("													class=\"ion-ios-arrow-forward\"></span></a>\n");
      out.write("											</p>\n");
      out.write("										</div>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"col-md-12\">\n");
      out.write("									<div class=\"blog-entry ftco-animate d-md-flex\">\n");
      out.write("										<a href=\"single.html\" class=\"img img-2\"\n");
      out.write("											style=\"background-image: url(/andrea-master/images/image_10.jpg);\"></a>\n");
      out.write("										<div class=\"text text-2 pl-md-4\">\n");
      out.write("											<h3 class=\"mb-2\">\n");
      out.write("												<a href=\"single.html\">You Can't Blame Gravity for\n");
      out.write("													Falling in Love</a>\n");
      out.write("											</h3>\n");
      out.write("											<div class=\"meta-wrap\">\n");
      out.write("												<p class=\"meta\">\n");
      out.write("													<span>Dec 14, 2018</span> <span><a\n");
      out.write("														href=\"single.html\">Lifestyle</a></span> <span>5 Comment</span>\n");
      out.write("												</p>\n");
      out.write("											</div>\n");
      out.write("											<p class=\"mb-4\">A small river named Duden flows by their\n");
      out.write("												place and supplies it with the necessary regelialia.</p>\n");
      out.write("											<p>\n");
      out.write("												<a href=\"#\" class=\"btn-custom\">Read More <span\n");
      out.write("													class=\"ion-ios-arrow-forward\"></span></a>\n");
      out.write("											</p>\n");
      out.write("										</div>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"col-md-12\">\n");
      out.write("									<div class=\"blog-entry ftco-animate d-md-flex\">\n");
      out.write("										<a href=\"single.html\" class=\"img img-2\"\n");
      out.write("											style=\"background-image: url(/andrea-master/images/image_11.jpg);\"></a>\n");
      out.write("										<div class=\"text text-2 pl-md-4\">\n");
      out.write("											<h3 class=\"mb-2\">\n");
      out.write("												<a href=\"single.html\">You Can't Blame Gravity for\n");
      out.write("													Falling in Love</a>\n");
      out.write("											</h3>\n");
      out.write("											<div class=\"meta-wrap\">\n");
      out.write("												<p class=\"meta\">\n");
      out.write("													<span><i class=\"icon-calendar mr-2\"></i>June 28,\n");
      out.write("														2019</span> <span><a href=\"single.html\"><i\n");
      out.write("															class=\"icon-folder-o mr-2\"></i>Travel</a></span> <span><i\n");
      out.write("														class=\"icon-comment2 mr-2\"></i>5 Comment</span>\n");
      out.write("												</p>\n");
      out.write("											</div>\n");
      out.write("											<p class=\"mb-4\">A small river named Duden flows by their\n");
      out.write("												place and supplies it with the necessary regelialia.</p>\n");
      out.write("											<p>\n");
      out.write("												<a href=\"#\" class=\"btn-custom\">Read More <span\n");
      out.write("													class=\"ion-ios-arrow-forward\"></span></a>\n");
      out.write("											</p>\n");
      out.write("										</div>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"col-md-12\">\n");
      out.write("									<div class=\"blog-entry ftco-animate d-md-flex\">\n");
      out.write("										<a href=\"single.html\" class=\"img img-2\"\n");
      out.write("											style=\"background-image: url(/andrea-master/images/image_12.jpg);\"></a>\n");
      out.write("										<div class=\"text text-2 pl-md-4\">\n");
      out.write("											<h3 class=\"mb-2\">\n");
      out.write("												<a href=\"single.html\">You Can't Blame Gravity for\n");
      out.write("													Falling in Love</a>\n");
      out.write("											</h3>\n");
      out.write("											<div class=\"meta-wrap\">\n");
      out.write("												<p class=\"meta\">\n");
      out.write("													<span><i class=\"icon-calendar mr-2\"></i>June 28,\n");
      out.write("														2019</span> <span><a href=\"single.html\"><i\n");
      out.write("															class=\"icon-folder-o mr-2\"></i>Travel</a></span> <span><i\n");
      out.write("														class=\"icon-comment2 mr-2\"></i>5 Comment</span>\n");
      out.write("												</p>\n");
      out.write("											</div>\n");
      out.write("											<p class=\"mb-4\">A small river named Duden flows by their\n");
      out.write("												place and supplies it with the necessary regelialia.</p>\n");
      out.write("											<p>\n");
      out.write("												<a href=\"#\" class=\"btn-custom\">Read More <span\n");
      out.write("													class=\"ion-ios-arrow-forward\"></span></a>\n");
      out.write("											</p>\n");
      out.write("										</div>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("							<!-- END-->\n");
      out.write("							<div class=\"row\">\n");
      out.write("								<div class=\"col\">\n");
      out.write("									<div class=\"block-27\">\n");
      out.write("										<ul>\n");
      out.write("											<li><a href=\"#\">&lt;</a></li>\n");
      out.write("											<li class=\"active\"><span>1</span></li>\n");
      out.write("											<li><a href=\"#\">2</a></li>\n");
      out.write("											<li><a href=\"#\">3</a></li>\n");
      out.write("											<li><a href=\"#\">4</a></li>\n");
      out.write("											<li><a href=\"#\">5</a></li>\n");
      out.write("											<li><a href=\"#\">&gt;</a></li>\n");
      out.write("										</ul>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"col-xl-4 sidebar ftco-animate bg-light pt-5\">\n");
      out.write("							<div class=\"sidebar-box pt-md-4\">\n");
      out.write("								<form action=\"#\" class=\"search-form\">\n");
      out.write("									<div class=\"form-group\">\n");
      out.write("										<span class=\"icon icon-search\"></span> <input type=\"text\"\n");
      out.write("											class=\"form-control\"\n");
      out.write("											placeholder=\"Type a keyword and hit enter\">\n");
      out.write("									</div>\n");
      out.write("								</form>\n");
      out.write("							</div>\n");
      out.write("							<div class=\"sidebar-box ftco-animate\">\n");
      out.write("								<h3 class=\"sidebar-heading\">Categories</h3>\n");
      out.write("								<ul class=\"categories\">\n");
      out.write("									<li><a href=\"#\">Fashion <span>(6)</span></a></li>\n");
      out.write("									<li><a href=\"#\">Technology <span>(8)</span></a></li>\n");
      out.write("									<li><a href=\"#\">Travel <span>(2)</span></a></li>\n");
      out.write("									<li><a href=\"#\">Food <span>(2)</span></a></li>\n");
      out.write("									<li><a href=\"#\">Photography <span>(7)</span></a></li>\n");
      out.write("								</ul>\n");
      out.write("							</div>\n");
      out.write("\n");
      out.write("							<div class=\"sidebar-box ftco-animate\">\n");
      out.write("								<h3 class=\"sidebar-heading\">Popular Articles</h3>\n");
      out.write("								<div class=\"block-21 mb-4 d-flex\">\n");
      out.write("									<a class=\"blog-img mr-4\"\n");
      out.write("										style=\"background-image: url(/andrea-master/images/image_1.jpg);\"></a>\n");
      out.write("									<div class=\"text\">\n");
      out.write("										<h3 class=\"heading\">\n");
      out.write("											<a href=\"#\">Even the all-powerful Pointing has no control</a>\n");
      out.write("										</h3>\n");
      out.write("										<div class=\"meta\">\n");
      out.write("											<div>\n");
      out.write("												<a href=\"#\"><span class=\"icon-calendar\"></span> June 28,\n");
      out.write("													2019</a>\n");
      out.write("											</div>\n");
      out.write("											<div>\n");
      out.write("												<a href=\"#\"><span class=\"icon-person\"></span> Dave Lewis</a>\n");
      out.write("											</div>\n");
      out.write("											<div>\n");
      out.write("												<a href=\"#\"><span class=\"icon-chat\"></span> 19</a>\n");
      out.write("											</div>\n");
      out.write("										</div>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"block-21 mb-4 d-flex\">\n");
      out.write("									<a class=\"blog-img mr-4\"\n");
      out.write("										style=\"background-image: url(/andrea-master/images/image_2.jpg);\"></a>\n");
      out.write("									<div class=\"text\">\n");
      out.write("										<h3 class=\"heading\">\n");
      out.write("											<a href=\"#\">Even the all-powerful Pointing has no control</a>\n");
      out.write("										</h3>\n");
      out.write("										<div class=\"meta\">\n");
      out.write("											<div>\n");
      out.write("												<a href=\"#\"><span class=\"icon-calendar\"></span> June 28,\n");
      out.write("													2019</a>\n");
      out.write("											</div>\n");
      out.write("											<div>\n");
      out.write("												<a href=\"#\"><span class=\"icon-person\"></span> Dave Lewis</a>\n");
      out.write("											</div>\n");
      out.write("											<div>\n");
      out.write("												<a href=\"#\"><span class=\"icon-chat\"></span> 19</a>\n");
      out.write("											</div>\n");
      out.write("										</div>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"block-21 mb-4 d-flex\">\n");
      out.write("									<a class=\"blog-img mr-4\"\n");
      out.write("										style=\"background-image: url(/andrea-master/images/image_3.jpg);\"></a>\n");
      out.write("									<div class=\"text\">\n");
      out.write("										<h3 class=\"heading\">\n");
      out.write("											<a href=\"#\">Even the all-powerful Pointing has no control</a>\n");
      out.write("										</h3>\n");
      out.write("										<div class=\"meta\">\n");
      out.write("											<div>\n");
      out.write("												<a href=\"#\"><span class=\"icon-calendar\"></span> June 28,\n");
      out.write("													2019</a>\n");
      out.write("											</div>\n");
      out.write("											<div>\n");
      out.write("												<a href=\"#\"><span class=\"icon-person\"></span> Dave Lewis</a>\n");
      out.write("											</div>\n");
      out.write("											<div>\n");
      out.write("												<a href=\"#\"><span class=\"icon-chat\"></span> 19</a>\n");
      out.write("											</div>\n");
      out.write("										</div>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("\n");
      out.write("							<div class=\"sidebar-box ftco-animate\">\n");
      out.write("								<h3 class=\"sidebar-heading\">Tag Cloud</h3>\n");
      out.write("								<ul class=\"tagcloud\">\n");
      out.write("									<a href=\"#\" class=\"tag-cloud-link\">animals</a>\n");
      out.write("									<a href=\"#\" class=\"tag-cloud-link\">human</a>\n");
      out.write("									<a href=\"#\" class=\"tag-cloud-link\">people</a>\n");
      out.write("									<a href=\"#\" class=\"tag-cloud-link\">cat</a>\n");
      out.write("									<a href=\"#\" class=\"tag-cloud-link\">dog</a>\n");
      out.write("									<a href=\"#\" class=\"tag-cloud-link\">nature</a>\n");
      out.write("									<a href=\"#\" class=\"tag-cloud-link\">leaves</a>\n");
      out.write("									<a href=\"#\" class=\"tag-cloud-link\">food</a>\n");
      out.write("								</ul>\n");
      out.write("							</div>\n");
      out.write("\n");
      out.write("							<div class=\"sidebar-box subs-wrap img py-4\"\n");
      out.write("								style=\"background-image: url(/andrea-master/images/bg_1.jpg);\">\n");
      out.write("								<div class=\"overlay\"></div>\n");
      out.write("								<h3 class=\"mb-4 sidebar-heading\">Newsletter</h3>\n");
      out.write("								<p class=\"mb-4\">Far far away, behind the word mountains, far\n");
      out.write("									from the countries Vokalia</p>\n");
      out.write("								<form action=\"#\" class=\"subscribe-form\">\n");
      out.write("									<div class=\"form-group\">\n");
      out.write("										<input type=\"text\" class=\"form-control\"\n");
      out.write("											placeholder=\"Email Address\"> <input type=\"submit\"\n");
      out.write("											value=\"Subscribe\" class=\"mt-2 btn btn-white submit\">\n");
      out.write("									</div>\n");
      out.write("								</form>\n");
      out.write("							</div>\n");
      out.write("\n");
      out.write("							<div class=\"sidebar-box ftco-animate\">\n");
      out.write("								<h3 class=\"sidebar-heading\">Archives</h3>\n");
      out.write("								<ul class=\"categories\">\n");
      out.write("									<li><a href=\"#\">Decob14 2018 <span>(10)</span></a></li>\n");
      out.write("									<li><a href=\"#\">September 2018 <span>(6)</span></a></li>\n");
      out.write("									<li><a href=\"#\">August 2018 <span>(8)</span></a></li>\n");
      out.write("									<li><a href=\"#\">July 2018 <span>(2)</span></a></li>\n");
      out.write("									<li><a href=\"#\">June 2018 <span>(7)</span></a></li>\n");
      out.write("									<li><a href=\"#\">May 2018 <span>(5)</span></a></li>\n");
      out.write("								</ul>\n");
      out.write("							</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("							<div class=\"sidebar-box ftco-animate\">\n");
      out.write("								<h3 class=\"sidebar-heading\">Paragraph</h3>\n");
      out.write("								<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.\n");
      out.write("									Ducimus itaque, autem necessitatibus voluptate quod mollitia\n");
      out.write("									delectus aut.</p>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("						<!-- END COL -->\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</section>\n");
      out.write("		</div>\n");
      out.write("		<!-- END COLORLIB-MAIN -->\n");
      out.write("	</div>\n");
      out.write("	<!-- END COLORLIB-PAGE -->\n");
      out.write("\n");
      out.write("	<!-- loader -->\n");
      out.write("	<div id=\"ftco-loader\" class=\"fullscreen\">\n");
      out.write("		<svg class=\"circular\" width=\"48px\" height=\"48px\">\n");
      out.write("			<circle class=\"path-bg\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\"\n");
      out.write("				stroke-width=\"4\" stroke=\"#eeeeee\"></circle>\n");
      out.write("			<circle class=\"path\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\"\n");
      out.write("				stroke-width=\"4\" stroke-miterlimit=\"10\" stroke=\"#F96D00\"></circle></svg>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("	<script src=\"/andrea-master/js/jquery.min.js\"></script>\n");
      out.write("	<script src=\"/andrea-master/js/jquery-migrate-3.0.1.min.js\"></script>\n");
      out.write("	<script src=\"/andrea-master/js/popper.min.js\"></script>\n");
      out.write("	<script src=\"/andrea-master/js/bootstrap.min.js\"></script>\n");
      out.write("	<script src=\"/andrea-master/js/jquery.easing.1.3.js\"></script>\n");
      out.write("	<script src=\"/andrea-master/js/jquery.waypoints.min.js\"></script>\n");
      out.write("	<script src=\"/andrea-master/js/jquery.stellar.min.js\"></script>\n");
      out.write("	<script src=\"/andrea-master/js/owl.carousel.min.js\"></script>\n");
      out.write("	<script src=\"/andrea-master/js/jquery.magnific-popup.min.js\"></script>\n");
      out.write("	<script src=\"/andrea-master/js/aos.js\"></script>\n");
      out.write("	<script src=\"/andrea-master/js/jquery.animateNumber.min.js\"></script>\n");
      out.write("	<script src=\"/andrea-master/js/scrollax.min.js\"></script>\n");
      out.write("	<script src=\"/andrea-master/js/main.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
