/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.66
 * Generated at: 2021-11-15 16:40:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.chat;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import poly.util.CmmUtil;
import static poly.util.CmmUtil.nvl;

public final class chatting_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/view/sidebar.jsp", Long.valueOf(1636648577735L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("static poly.util.CmmUtil.nvl");
    _jspx_imports_classes.add("poly.util.CmmUtil");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

	String study_name = (String)request.getAttribute("study_name");
	String study_seq = (String)request.getAttribute("study_seq");
	String user_id = (String) session.getAttribute("user_id");

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("<title>Chatting</title>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta name=\"viewport\"\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("<link\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700\"\n");
      out.write("	rel=\"stylesheet\">\n");
      out.write("<link\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i&display=swap\"\n");
      out.write("	rel=\"stylesheet\">\n");
      out.write("<link\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Abril+Fatface&display=swap\"\n");
      out.write("	rel=\"stylesheet\">\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"/andrea-master/css/open-iconic-bootstrap.min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/animate.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/owl.carousel.min.css\">\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"/andrea-master/css/owl.theme.default.min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/magnific-popup.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/aos.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/ionicons.min.css\">\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"/andrea-master/css/bootstrap-datepicker.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/jquery.timepicker.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/flaticon.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/icomoon.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/style.css\">\n");
      out.write("\n");
      out.write("<!-- profile -->\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/profile.css\">\n");
      out.write("<link href=\"//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css\" rel=\"stylesheet\" id=\"bootstrap-css\">\n");
      out.write("<script src=\"//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js\"></script>\n");
      out.write("<!-- profile -->\n");
      out.write("\n");
      out.write("<!-- chatting -->\n");
      out.write("<style type=\"text/css\">\n");
      out.write("	.chat_window {\n");
      out.write("	  \n");
      out.write("	  width: 100%;\n");
      out.write("	  max-width: 800px;\n");
      out.write("	  height: 600px;\n");
      out.write("	  border-radius: 10px;\n");
      out.write("	  background-color: #fff;\n");
      out.write("	  \n");
      out.write("	  box-shadow: 0 10px 20px rgba(0, 0, 0, 0.15);\n");
      out.write("	  background-color: #f8f8f8;\n");
      out.write("	  overflow: hidden;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	.top_menu {\n");
      out.write("	  background-color: #fff;\n");
      out.write("	  width: 100%;\n");
      out.write("	  padding: 20px 0 15px;\n");
      out.write("	  box-shadow: 0 1px 30px rgba(0, 0, 0, 0.1);\n");
      out.write("	}\n");
      out.write("	.top_menu .buttons {\n");
      out.write("	  margin: 3px 0 0 20px;\n");
      out.write("	  position: absolute;\n");
      out.write("	}\n");
      out.write("	.top_menu .buttons .button {\n");
      out.write("	  width: 16px;\n");
      out.write("	  height: 16px;\n");
      out.write("	  border-radius: 50%;\n");
      out.write("	  display: inline-block;\n");
      out.write("	  margin-right: 10px;\n");
      out.write("	  position: relative;\n");
      out.write("	}\n");
      out.write("	.top_menu .buttons .button.close {\n");
      out.write("	  background-color: #f5886e;\n");
      out.write("	}\n");
      out.write("	.top_menu .buttons .button.minimize {\n");
      out.write("	  background-color: #fdbf68;\n");
      out.write("	}\n");
      out.write("	.top_menu .buttons .button.maximize {\n");
      out.write("	  background-color: #a3d063;\n");
      out.write("	}\n");
      out.write("	.top_menu .title {\n");
      out.write("	  text-align: center;\n");
      out.write("	  color: #bcbdc0;\n");
      out.write("	  font-size: 20px;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	.messages {\n");
      out.write("	  position: relative;\n");
      out.write("	  list-style: none;\n");
      out.write("	  padding: 20px 10px 0 10px;\n");
      out.write("	  margin: 0;\n");
      out.write("	  height: 440px;\n");
      out.write("	  overflow: scroll;\n");
      out.write("	}\n");
      out.write("	.messages .message {\n");
      out.write("	  clear: both;\n");
      out.write("	  overflow: hidden;\n");
      out.write("	  margin-bottom: 20px;\n");
      out.write("	  transition: all 0.5s linear;\n");
      out.write("	  opacity: 0;\n");
      out.write("	}\n");
      out.write("	.messages .message.left .avatar {\n");
      out.write("	  background-color: #f5886e;\n");
      out.write("	  float: left;\n");
      out.write("	}\n");
      out.write("	.messages .message.left .text_wrapper {\n");
      out.write("	  background-color: #ffe6cb;\n");
      out.write("	  margin-left: 20px;\n");
      out.write("	}\n");
      out.write("	.messages .message.left .text_wrapper::after, .messages .message.left .text_wrapper::before {\n");
      out.write("	  right: 100%;\n");
      out.write("	  border-right-color: #ffe6cb;\n");
      out.write("	}\n");
      out.write("	.messages .message.left .text {\n");
      out.write("	  color: #c48843;\n");
      out.write("	}\n");
      out.write("	.messages .message.right .avatar {\n");
      out.write("	  background-color: #fdbf68;\n");
      out.write("	  float: right;\n");
      out.write("	}\n");
      out.write("	.messages .message.right .text_wrapper {\n");
      out.write("	  background-color: #c7eafc;\n");
      out.write("	  margin-right: 20px;\n");
      out.write("	  float: right;\n");
      out.write("	}\n");
      out.write("	.messages .message.right .text_wrapper::after, .messages .message.right .text_wrapper::before {\n");
      out.write("	  left: 100%;\n");
      out.write("	  border-left-color: #c7eafc;\n");
      out.write("	}\n");
      out.write("	.messages .message.right .text {\n");
      out.write("	  color: #45829b;\n");
      out.write("	}\n");
      out.write("	.messages .message.appeared {\n");
      out.write("	  opacity: 1;\n");
      out.write("	}\n");
      out.write("	.messages .message .avatar {\n");
      out.write("	  width: 60px;\n");
      out.write("	  height: 60px;\n");
      out.write("	  border-radius: 50%;\n");
      out.write("	  display: inline-block;\n");
      out.write("	}\n");
      out.write("	.messages .message .text_wrapper {\n");
      out.write("	  display: inline-block;\n");
      out.write("	  padding: 20px;\n");
      out.write("	  border-radius: 6px;\n");
      out.write("	  width: calc(100% - 85px);\n");
      out.write("	  min-width: 100px;\n");
      out.write("	  position: relative;\n");
      out.write("	}\n");
      out.write("	.messages .message .text_wrapper::after, .messages .message .text_wrapper:before {\n");
      out.write("	  top: 18px;\n");
      out.write("	  border: solid transparent;\n");
      out.write("	  content: \" \";\n");
      out.write("	  height: 0;\n");
      out.write("	  width: 0;\n");
      out.write("	  position: absolute;\n");
      out.write("	  pointer-events: none;\n");
      out.write("	}\n");
      out.write("	.messages .message .text_wrapper::after {\n");
      out.write("	  border-width: 13px;\n");
      out.write("	  margin-top: 0px;\n");
      out.write("	}\n");
      out.write("	.messages .message .text_wrapper::before {\n");
      out.write("	  border-width: 15px;\n");
      out.write("	  margin-top: -2px;\n");
      out.write("	}\n");
      out.write("	.messages .message .text_wrapper .text {\n");
      out.write("	  font-size: 18px;\n");
      out.write("	  font-weight: 300;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	.bottom_wrapper {\n");
      out.write("	  position: relative;\n");
      out.write("	  width: 100%;\n");
      out.write("	  background-color: #fff;\n");
      out.write("	  padding: 20px 20px;\n");
      out.write("	  bottom: 0;\n");
      out.write("	  padding-left: 5px;\n");
      out.write("	  padding-right: 5px;\n");
      out.write("	}\n");
      out.write("	.bottom_wrapper .message_input_wrapper {\n");
      out.write("	  display: inline-block;\n");
      out.write("	  height: 50px;\n");
      out.write("	  border-radius: 25px;\n");
      out.write("	  border: 1px solid #bcbdc0;\n");
      out.write("	  width: 75%;\n");
      out.write("	  position: relative;\n");
      out.write("	  padding: 0 20px;\n");
      out.write("	}\n");
      out.write("	.bottom_wrapper .message_input_wrapper .message_input {\n");
      out.write("	  border: none;\n");
      out.write("	  height: 100%;\n");
      out.write("	  box-sizing: border-box;\n");
      out.write("	  width: calc(100% - 40px);\n");
      out.write("	  position: absolute;\n");
      out.write("	  outline-width: 0;\n");
      out.write("	  color: gray;\n");
      out.write("	}\n");
      out.write("	.bottom_wrapper .send_message {\n");
      out.write("	  width: 24%;\n");
      out.write("	  height: 50px;\n");
      out.write("	  display: inline-block;\n");
      out.write("	  border-radius: 50px;\n");
      out.write("	  background-color: #a3d063;\n");
      out.write("	  border: 2px solid #a3d063;\n");
      out.write("	  color: #fff;\n");
      out.write("	  cursor: pointer;\n");
      out.write("	  transition: all 0.2s linear;\n");
      out.write("	  text-align: center;\n");
      out.write("	  float: right;\n");
      out.write("	}\n");
      out.write("	.bottom_wrapper .send_message:hover {\n");
      out.write("	  color: #a3d063;\n");
      out.write("	  background-color: #fff;\n");
      out.write("	}\n");
      out.write("	.bottom_wrapper .send_message .text {\n");
      out.write("	  font-size: 18px;\n");
      out.write("	  font-weight: 300;\n");
      out.write("	  display: inline-block;\n");
      out.write("	  line-height: 48px;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	.message_template {\n");
      out.write("	  display: none;\n");
      out.write("	}\n");
      out.write("</style>\n");
      out.write("<!-- chatting -->\n");
      out.write("</head>\n");
      out.write("<body data-aos-easing=\"slide\" data-aos-duration=\"800\" data-aos-delay=\"0\">\n");
      out.write("\n");
      out.write("	<!-- 전체 페이지 START-->\n");
      out.write("	<div id=\"colorlib-page\">\n");
      out.write("		<!-- START 왼쪽 NANI -->\n");
      out.write("		");
      out.write('\n');
      out.write('\n');


	String id = nvl((String)session.getAttribute("user_id"));
	String date = nvl((String)session.getAttribute("join_dt")); 

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<!-- 구글폰트 -->\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Do+Hyeon&family=Nanum+Pen+Script&display=swap\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<a href=\"#\" class=\"js-colorlib-nav-toggle colorlib-nav-toggle\"><i></i></a>\n");
      out.write("		<aside id=\"colorlib-aside\" role=\"complementary\" class=\"js-fullheight\"\n");
      out.write("			style=\"height: 812px;\">\n");
      out.write("			\n");
      out.write("			<nav id=\"colorlib-main-menu\" role=\"navigation\">\n");
      out.write("			<a href=\"single.html\" class=\"img img-2\" style=\"background-image: url(/andrea-master/images/image_1.jpg);\"></a>\n");
      out.write("			<div class=\"colorlib-active\">\n");
      out.write("			<ul>\n");
      out.write("				<li>\n");
      out.write("					");
if(date.isEmpty()) { 
      out.write("\n");
      out.write("						<a href=\"/user/login.do\" style=\"font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive; font-size: 32px;\">가입 하시겠습니까?</a>\n");
      out.write("					");
 } else { 
      out.write("\n");
      out.write("						<a href=\"#\" style=\"font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive; font-size: 24px;\" method=post>첫방문  : ");
      out.print(date );
      out.write("</a>\n");
      out.write("					");
} 
      out.write("\n");
      out.write("				\n");
      out.write("				</li>\n");
      out.write("				<li>\n");
      out.write("					");
if(id.isEmpty()) { 
      out.write("\n");
      out.write("						<a href=\"/user/login.do\" style= \"font-family: 'Nanum Pen Script', cursive; font-size: 20px; padding-left: 70px;\">Sign in</a>\n");
      out.write("					");
 } else { 
      out.write("\n");
      out.write("						<a href=\"/user/logOut.do\" style=\" font-family: 'Nanum Pen Script', cursive; font-size: 24px; padding-left: 40px;\">");
      out.print(id );
      out.write(" 님 Log out</a>\n");
      out.write("					");
} 
      out.write("\n");
      out.write("				</li>\n");
      out.write("			</ul>\n");
      out.write("		</div>\n");
      out.write("		<hr style=\" width: 90%; height: 1.5px; border: none; background-color: #666666;\"/>\n");
      out.write("				<ul class=\"nav2\">\n");
      out.write("					<li class=\"colorlib-active\"><a href=\"/spoilbroth/mystudy.do\">Home</a></li>\n");
      out.write("					<li class=\"nana\"><a href=\"/mbti/mbtimain.do\">MBTI Analysis</a></li>\n");
      out.write("					<li class=\"nana2\"><a href=\"/study/match.do\">Study Matching</a></li>\n");
      out.write("					<li class=\"nana3\"><a href=\"/study/contest.do\">Study Imformation</a></li>\n");
      out.write("					<li class=\"nana4\"><a href=\"/mypage/setting.do\">Setting</a></li>\n");
      out.write("				</ul>\n");
      out.write("			</nav>\n");
      out.write("\n");
      out.write("			<div class=\"colorlib-footer\" style=\"padding-bottom: 20px;\">\n");
      out.write("				<h1 id=\"colorlib-logo\" class=\"mb-4\">\n");
      out.write("					<a href=\"/spoilbroth/mystudy.do\" style=\"background-image: url(/andrea-master/images/bg_1.jpg); font-size: 57px;\">Spoilbroth</a>\n");
      out.write("				</h1>\n");
      out.write("				<span style=\"font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive; font-size: 28px;\">요리사가 너무 많으면 수프를 망친다.</span>\n");
      out.write("				<div class=\"mb-4\">\n");
      out.write("					<h3>Subscribe for Spoilbroth</h3>\n");
      out.write("					<form action=\"#\" class=\"colorlib-subscribe-form\">\n");
      out.write("						<div class=\"form-group d-flex\">\n");
      out.write("							<div class=\"icon\">\n");
      out.write("								<span class=\"icon-paper-plane\"></span>\n");
      out.write("							</div>\n");
      out.write("							<input type=\"text\" class=\"form-control\"\n");
      out.write("								placeholder=\"Enter Email Address\">\n");
      out.write("						</div>\n");
      out.write("					</form>\n");
      out.write("				</div>\n");
      out.write("				\n");
      out.write("			</div>\n");
      out.write("		</aside>\n");
      out.write("\n");
      out.write("\n");
      out.write("<script src=\"/andrea-master/js/jquery.min.js\"></script>\n");
      out.write("</body>\n");
      out.write("<script>\n");
      out.write("$(function(){\n");
      out.write("    var url = window.location.pathname;  \n");
      out.write("    var activePage = url.substring(url.lastIndexOf('/')+1);\n");
      out.write("    console.log(\"activePage: \" + activePage);\n");
      out.write("    \n");
      out.write("    $('.nav2 li a').each(function(){  \n");
      out.write("        var currentPage = this.href.substring(this.href.lastIndexOf('/')+1);\n");
      out.write("		console.log(\"currentPage : \"+currentPage)\n");
      out.write("		\n");
      out.write("        if (activePage == currentPage) {\n");
      out.write("        	$(\".nav2\").find(\".colorlib-active\").removeClass(\"colorlib-active\");\n");
      out.write("            $(this).parent().addClass('colorlib-active');\n");
      out.write("            $(this).addClass('colorlib-active');\n");
      out.write("            \n");
      out.write("        }else if(activePage == \"mbtianalysis.do\"){\n");
      out.write("        	$(\".nav2\").find(\".colorlib-active\").removeClass(\"colorlib-active\");\n");
      out.write("        	$('.nana').addClass('colorlib-active');\n");
      out.write("        }else if(activePage == \"match2.do\"){\n");
      out.write("        	$(\".nav2\").find(\".colorlib-active\").removeClass(\"colorlib-active\");\n");
      out.write("        	$('.nana2').addClass('colorlib-active');\n");
      out.write("        }\n");
      out.write("    });\n");
      out.write("})\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("</html>");
      out.write("\n");
      out.write("		<!-- END 왼쪽 NANI -->\n");
      out.write("\n");
      out.write("		<!-- START 상단 NANI -->\n");
      out.write("		<div class=\"padding\" style=\"padding-bottom: 55px;\"></div>\n");
      out.write("		<div class=\"sidebar-heading\"\n");
      out.write("			style=\"text-align: center; position: fixed; top: 0; width: 100%; height: 70px; background-color: #fff; z-index: 5; padding-top: 20px; font-weight: 500; color: black;\">\n");
      out.write("			<div class=\"hh\" style=\"font-size: 23px; height: 32px;\">\n");
      out.write("				<span>S</span><span>T</span><span>U</span><span>D</span><span>Y</span><span>&nbsp;</span><span>C</span><span>H</span><span>A</span><span>T</span><span>T</span><span>I</span><span>N</span><span>G</span>\n");
      out.write("			</div>\n");
      out.write("			<hr\n");
      out.write("				style=\"width: 90%; height: 1.5px; border: none; background-color: #666666;\">\n");
      out.write("		</div>\n");
      out.write("		<!-- END 상단 NANI -->\n");
      out.write("\n");
      out.write("		<!-- 메인 페이지 START-->\n");
      out.write("		<div id=\"colorlib-main\">\n");
      out.write("			<section class=\"ftco-section ftco-no-pt ftco-no-pb\">\n");
      out.write("				<div class=\"container\">\n");
      out.write("\n");
      out.write("					<!-- 왼쪽 오른쪽 2분할 -->\n");
      out.write("					<div class=\"row d-flex\">\n");
      out.write("\n");
      out.write("						<!-- 왼쪽 스크립트 -->\n");
      out.write("						<div class=\"col-xl-8 px-md-5\" style=\"background-color: #f7fbff;\">\n");
      out.write("							<!-- 스터디 개설  START -->\n");
      out.write("							<div class=\"\" style=\"margin-left: 20px\">\n");
      out.write("								<label\n");
      out.write("									style=\"font-size: 30px; font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive; margin-top: 18px; margin-bottom: -8px;\">\n");
      out.write("									");
      out.print(study_name);
      out.write(" 팀의 채팅창\n");
      out.write("								</label>\n");
      out.write("								<label\n");
      out.write("									style=\"font-size: 20px; font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive; margin-top: 18px; margin-bottom: -8px; float:right;\">\n");
      out.write("									By ");
      out.print(user_id);
      out.write("\n");
      out.write("								</label>\n");
      out.write("							</div>\n");
      out.write("							<hr>\n");
      out.write("							<div class=\"\">\n");
      out.write("								<!-- <div class=\"d-flex card p-3\" style=\"magin: -11px;\"> -->\n");
      out.write("									");
      out.write("\n");
      out.write("									<div class=\"buttons\">\n");
      out.write("									<button class=\"btn btn-info\" type=\"button\" onclick=\"openSocket()\" style=\"font-size: 12px;\">대화방참여</button>\n");
      out.write("									<button class=\"btn btn-warning\" type=\"button\" onclick=\"closeSocket();\" style=\"font-size: 12px;\">대화방 나가기</button>\n");
      out.write("									<button class=\"btn btn-success\" type=\"button\" onclick=\"pre();\" style=\"font-size: 12px;\">이전 메시지 불러오기</button>\n");
      out.write("									</div>\n");
      out.write("									<div class=\"chat_window\">\n");
      out.write("										<div class=\"top_menu\">\n");
      out.write("											<div class=\"buttons\">\n");
      out.write("												<div class=\"button close\"></div>\n");
      out.write("												<div class=\"button minimize\"></div>\n");
      out.write("												<div class=\"button maximize\"></div>\n");
      out.write("											</div>\n");
      out.write("											<div class=\"title\">Chat</div>\n");
      out.write("										</div>\n");
      out.write("										<!-- 메시지 창 -->\n");
      out.write("										<div id =\"chat\"></div>\n");
      out.write("										<ul class=\"messages\"></ul>\n");
      out.write("										\n");
      out.write("										<div class=\"bottom_wrapper clearfix\">\n");
      out.write("											<div class=\"message_input_wrapper\">\n");
      out.write("												<input type=\"text\" id=\"sender\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" style=\"display: none;\">\n");
      out.write("												<input type=\"text\" class=\"message_input\" placeholder=\"Type your message here...\" />\n");
      out.write("											</div>\n");
      out.write("										<!-- Send 메시지 -->\n");
      out.write("											<div class=\"send_message\" onclick=\"send();\">\n");
      out.write("												<div class=\"icon\"></div>\n");
      out.write("												<div class=\"text\">Send</div>\n");
      out.write("											</div>\n");
      out.write("										</div>\n");
      out.write("									</div>\n");
      out.write("									<div class=\"message_template\">\n");
      out.write("										<li class=\"message\"><div class=\"avatar\"></div>\n");
      out.write("											<div class=\"text_wrapper\">\n");
      out.write("												<div class=\"text\"></div>\n");
      out.write("											</div></li>\n");
      out.write("									</div>\n");
      out.write("\n");
      out.write("									<hr style=\"margin-top: 10px; margin-bottom: 0px;\" />\n");
      out.write("									\n");
      out.write("									\n");
      out.write("								<!-- </div> -->\n");
      out.write("							</div>\n");
      out.write("							<!-- 왼쪽 스크립트 끝 -->\n");
      out.write("\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</section>\n");
      out.write("		</div>\n");
      out.write("		<!-- 메인 페이지 END-->\n");
      out.write("	</div>\n");
      out.write("	<!-- 전체 페이지 END-->\n");
      out.write("\n");
      out.write("	<!-- loader -->\n");
      out.write("\n");
      out.write("\n");
      out.write("	<script src=\"/andrea-master/js/jquery.min.js\"></script>\n");
      out.write("	<script src=\"/andrea-master/js/jquery-migrate-3.0.1.min.js\"></script>\n");
      out.write("	<script src=\"/andrea-master/js/popper.min.js\"></script>\n");
      out.write("	<script src=\"/andrea-master/js/bootstrap.min.js\"></script>\n");
      out.write("	<script src=\"/andrea-master/js/jquery.easing.1.3.js\"></script>\n");
      out.write("	<script src=\"/andrea-master/js/jquery.waypoints.min.js\"></script>\n");
      out.write("	<script src=\"/andrea-master/js/jquery.stellar.min.js\"></script>\n");
      out.write("	<script src=\"/andrea-master/js/owl.carousel.min.js\"></script>\n");
      out.write("	<script src=\"/andrea-master/js/jquery.magnific-popup.min.js\"></script>\n");
      out.write("	<script src=\"/andrea-master/js/aos.js\"></script>\n");
      out.write("	<script src=\"/andrea-master/js/jquery.animateNumber.min.js\"></script>\n");
      out.write("	<script src=\"/andrea-master/js/scrollax.min.js\"></script>\n");
      out.write("	<script src=\"/andrea-master/js/main.js\"></script>\n");
      out.write("	<script\n");
      out.write("		src=\"https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js\"></script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("	function getDatetime() {\n");
      out.write("		let _date = new Date();\n");
      out.write("		let _hours = _date.getHours();\n");
      out.write("		let _min = _date.getMinutes();\n");
      out.write("		_hours = _hours < 10 ? '0' + _hours : _hours\n");
      out.write("		_min = _min < 10 ? '0' + _min : _min\n");
      out.write("		return _hours + ':' + _min;\n");
      out.write("	}\n");
      out.write("	/* ##### websocket js start ##### */\n");
      out.write("	let ws;\n");
      out.write("	function openSocket() {\n");
      out.write("		console.log(\"openSocket\");\n");
      out.write("		if (ws !== undefined && ws.readyState !== WebSocket.CLOSED) {\n");
      out.write("			console.log(\"WebSocket is already opened.\");\n");
      out.write("			return;\n");
      out.write("		}\n");
      out.write("		//웹소켓 객체 만드는 코드\n");
      out.write("		ws = new WebSocket(\"ws://13.125.99.115:8080/echo.do\");\n");
      out.write("\n");
      out.write("		ws.onopen = function(event) {\n");
      out.write("			if (event.data === undefined)\n");
      out.write("				return;\n");
      out.write("\n");
      out.write("			writeResponse(event.data);\n");
      out.write("		};\n");
      out.write("\n");
      out.write("		ws.onmessage = function(event) {\n");
      out.write("			writeResponse(event.data);\n");
      out.write("		};\n");
      out.write("		ws.onclose = function(event) {\n");
      out.write("			writeResponse(\"연결이 해제되었습니다.\");\n");
      out.write("		}\n");
      out.write("	}\n");
      out.write("	function send() {\n");
      out.write("		var text = $(\".message_input\").val() + \",\" + document.getElementById(\"sender\").value;\n");
      out.write("		console.log(\"text : \" +text)\n");
      out.write("		ws.send(text);\n");
      out.write("		text = \"\";\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		let chat_id = '");
      out.print(user_id );
      out.write("';\n");
      out.write("		let chat_dt = getDatetime();\n");
      out.write("		let study_seq = ");
      out.print(study_seq );
      out.write(";\n");
      out.write("		let study_name = '");
      out.print(study_name );
      out.write("';\n");
      out.write("		let chat_content = $(\".message_input\").val();\n");
      out.write("		\n");
      out.write("		console.log(\"chat_id : \" + chat_id)\n");
      out.write("		var param = {};\n");
      out.write("		\n");
      out.write("		param['chat_id'] = chat_id;\n");
      out.write("		param['chat_dt'] = chat_dt;\n");
      out.write("		param['study_seq'] = study_seq;\n");
      out.write("		param['study_name'] = study_name;\n");
      out.write("		param['chat_contents'] = chat_content;\n");
      out.write("		\n");
      out.write("		console.table(param);\n");
      out.write("		\n");
      out.write("		 $.ajax({\n");
      out.write("	         url: \"/chat/messageeForRedis.do\",\n");
      out.write("	         type: 'POST',\n");
      out.write("	         data: param, \n");
      out.write("	         success:function(result) {\n");
      out.write("	            console.log(result);\n");
      out.write("	         },\n");
      out.write("	         error:function(e) {\n");
      out.write("	            console.log(e);\n");
      out.write("	         }\n");
      out.write("	      })\n");
      out.write("		\n");
      out.write("		$('.message_input').val('');\n");
      out.write("	}\n");
      out.write("	function closeSocket() {\n");
      out.write("		ws.close();\n");
      out.write("	}\n");
      out.write("	function writeResponse(text) {\n");
      out.write("		console.log(\"text : \" + text);\n");
      out.write("		let _dateTime = getDatetime();\n");
      out.write("		/* console.log(json.res_msg);\n");
      out.write("		let resHTML = \"\";\n");
      out.write("		resHTML += '<li class=\"clearfix\">';\n");
      out.write("		resHTML += '<span class=\"chat-img\">';\n");
      out.write("		resHTML += '<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/andrea-master/images/ISFP.png\">';\n");
      out.write("		resHTML += '</span>';\n");
      out.write("		resHTML += '<div class=\"chat-body clearfix \" style=\"display:flex; margin-left:5px\";>';\n");
      out.write("		resHTML += '<span class=\"chat_time\">' + _dateTime\n");
      out.write("				+ '</span>&nbsp&nbsp&nbsp&nbsp';\n");
      out.write("		resHTML += '<p>' + text + '</p>';\n");
      out.write("		resHTML += '</div>';\n");
      out.write("		resHTML += '</li>'; */\n");
      out.write("		let res = \"\";\n");
      out.write("		var qqq = text.substring(1,2);\n");
      out.write("		console.log(\"qqq : \" + qqq);\n");
      out.write("		\n");
      out.write("		var user_id = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\n");
      out.write("		console.log(\"user_id : \" + user_id);\n");
      out.write("		if(qqq == \"나\"){\n");
      out.write("			res += '<li class=\"message left appeared\" id=\"chat_ul\">';\n");
      out.write("			res += '<div class=\"avatar\"></div>';\n");
      out.write("			res += '<div class=\"text_wrapper\">';\n");
      out.write("			res += '<div class=\"text\" style=\"font-size: 20px; font-family: \\'Do Hyeon\\', sans-serif; font-family: \\'Nanum Pen Script\\', cursive;  margin-bottom: -8px;\">'+ _dateTime + '&nbsp;&nbsp;' + text + '</div>';\n");
      out.write("			res += '</div>';\n");
      out.write("			res += '</li>';\n");
      out.write("		}else{\n");
      out.write("			res += '<li class=\"message right appeared\" id=\"chat_ul\">';\n");
      out.write("			res += '<div class=\"avatar\"></div>';\n");
      out.write("			res += '<div class=\"text_wrapper\">';\n");
      out.write("			res += '<div class=\"text\" style=\"font-size: 20px; font-family: \\'Do Hyeon\\', sans-serif; font-family: \\'Nanum Pen Script\\', cursive;  margin-bottom: -8px;\">'+ _dateTime + '&nbsp;&nbsp;' + text + '</div>';\n");
      out.write("			res += '</div>';\n");
      out.write("			res += '</li>';\n");
      out.write("		}\n");
      out.write("		$(\".messages\").append(res);\n");
      out.write("		$messages = $('.messages');\n");
      out.write("        return $messages.animate({ scrollTop: $messages.prop('scrollHeight') }, 300);\n");
      out.write("	}\n");
      out.write("	openSocket(); // websocket open\n");
      out.write("	window.onbeforeunload = function(e) {\n");
      out.write("		closeSocket() // 페이지 벗어나면 websocket close\n");
      out.write("	};\n");
      out.write("	/* ##### websocket js end ##### */\n");
      out.write("	function clearText() {\n");
      out.write("		console.log(messages.parentNode);\n");
      out.write("		messages.parentNode.removeChild(messages)\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	function pre(){\n");
      out.write("		console.log(\"pre start!!\");\n");
      out.write("		$.ajax({\n");
      out.write("	         url: \"/chat/messageeFromRedis.do\",\n");
      out.write("	         type: 'GET',\n");
      out.write("	         data: {\n");
      out.write("	        	 study_name : '");
      out.print(study_name);
      out.write("'\n");
      out.write("	         },\n");
      out.write("	         dataType: \"text\",\n");
      out.write("	         success:function(data) {\n");
      out.write("	            console.table(data);\n");
      out.write("	            \n");
      out.write("	            var result = data\n");
      out.write("	            /* $('#chat').html(data); */\n");
      out.write("	            $(\".messages\").append(data);\n");
      out.write("	            \n");
      out.write("	            \n");
      out.write("	           ");
      out.write("\n");
      out.write("	        	\n");
      out.write("	        	 /* console.log(\"data : \"+ data);\n");
      out.write("	        	 console.log(\"data.get[0] : \"+ data[0][0]['chat_contents']); */\n");
      out.write("	         },\n");
      out.write("	         error:function(e) {\n");
      out.write("	            console.log(e);\n");
      out.write("	         }\n");
      out.write("	      })\n");
      out.write("	      \n");
      out.write("		\n");
      out.write("	}\n");
      out.write("</script>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("	/* (function () {\n");
      out.write("	    var Message;\n");
      out.write("	    Message = function (arg) {\n");
      out.write("	        this.text = arg.text, this.message_side = arg.message_side;\n");
      out.write("	        this.draw = function (_this) {\n");
      out.write("	            return function () {\n");
      out.write("	                var $message;\n");
      out.write("	                $message = $($('.message_template').clone().html());\n");
      out.write("	                $message.attr('id','chat__ul').addClass(_this.message_side).find('.text').html(_this.text);\n");
      out.write("	                $('.messages').append($message);\n");
      out.write("	                return setTimeout(function () {\n");
      out.write("	                    return $message.addClass('appeared');\n");
      out.write("	                }, 0);\n");
      out.write("	            };\n");
      out.write("	        }(this);\n");
      out.write("	        return this;\n");
      out.write("	    };\n");
      out.write("	    $(function () {\n");
      out.write("	        var getMessageText, message_side, sendMessage;\n");
      out.write("	        message_side = 'right';\n");
      out.write("	        getMessageText = function () {\n");
      out.write("	            var $message_input;\n");
      out.write("	            $message_input = $('.message_input');\n");
      out.write("	            return $message_input.val();\n");
      out.write("	        };\n");
      out.write("	        sendMessage = function (text) {\n");
      out.write("	            var $messages, message;\n");
      out.write("	            if (text.trim() === '') {\n");
      out.write("	                return;\n");
      out.write("	            }\n");
      out.write("	            $('.message_input').val('');\n");
      out.write("	            $messages = $('.messages');\n");
      out.write("	            message_side = message_side === 'left' ? 'right' : 'left';\n");
      out.write("	            message = new Message({\n");
      out.write("	                text: text,\n");
      out.write("	                message_side: message_side\n");
      out.write("	            });\n");
      out.write("	            message.draw();\n");
      out.write("	            return $messages.animate({ scrollTop: $messages.prop('scrollHeight') }, 300);\n");
      out.write("	        };\n");
      out.write("	        $('.send_message').click(function (e) {\n");
      out.write("	            return sendMessage(getMessageText());\n");
      out.write("	        });\n");
      out.write("	        $('.message_input').keyup(function (e) {\n");
      out.write("	            if (e.which === 13) {\n");
      out.write("	                return sendMessage(getMessageText());\n");
      out.write("	            }\n");
      out.write("	        });\n");
      out.write("	        sendMessage('Hello Philip! :)');\n");
      out.write("	        setTimeout(function () {\n");
      out.write("	            return sendMessage('Hi Sandy! How are you?');\n");
      out.write("	        }, 1000);\n");
      out.write("	        return setTimeout(function () {\n");
      out.write("	            return sendMessage('I\\'m fine, thank you!');\n");
      out.write("	        }, 2000);\n");
      out.write("	    });\n");
      out.write("	}.call(this)); */\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
